name: Deploy InstantMail Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 186.202.57.159 > ~/.ssh/known_hosts

      - name: Deploy JAR to Server
        run: |
          JAR_NAME="instantmail-0.0.1-SNAPSHOT.jar"
          LOCAL_JAR_PATH="target/$JAR_NAME"
          REMOTE_SERVER="admin@186.202.57.159"
          REMOTE_JAR_DIR="/opt/instantmail"

          rsync -avz -e "ssh" $LOCAL_JAR_PATH $REMOTE_SERVER:$REMOTE_JAR_DIR/$JAR_NAME

          ssh $REMOTE_SERVER << EOF
            mv $REMOTE_JAR_DIR/$JAR_NAME $REMOTE_JAR_DIR/instantmail.jar
            sudo systemctl restart instantmail.service
          EOF